<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    protected $table = 'applications';


    public function job()
    {
        return $this->belongsTo('App\Model\JobPost', 'jobId', 'autoGeneratedJobId');
    }

    public function department()
    {
        return $this->belongsTo('App\Model\Department', 'departmentId', 'autoGeneratedDepartmentId');
    }
}
