<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    public function application()
    {
        return $this->hasMany('App\Model\Application', 'departmentId', 'autoGeneratedDepartmentId');
    }
}
