<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class JobPost extends Model
{
    protected $table = 'job_posts';

    public function department()
    {
        return $this->belongsTo('App\Model\Department', 'departmentId', 'autoGeneratedDepartmentId');
    }

    public function application()
    {
        return $this->hasMany('App\Model\Application', 'jobId', 'autoGeneratedJobId');
    }

}
