<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class Tertiobroadband extends Model
{
    protected $table = 'tertiobroadbands';

    public function application()
    {
        return $this->hasMany('App\Model\Application', 'tertiobroadbandId', 'autoGeneratedTertiobroadbandId');
    }
}
