@extends('layouts.frontEndMaster')
@section('content')
    <div class="col-lg-9 blog-main">
        Apply To : {{ $jobPost->jobTitle }}
          @if (Session::has('message'))
            <div class="text-success"> {{ Session::get('message') }}</div>
          @endif
        <hr/>
        <div class="row">
            {!! Form::open(array('url'=>'/apply-to-job/'.$jobPost->autoGeneratedJobId, 'method'=>'POST', 'class'=>'form', 'enctype'=>'multipart/form-data', 'role'=>'form')) !!}
            <div class="col-lg-6">
                <div class="form-group <?php  if($errors->has('fullName')){ echo 'has-error'; }?> ">
                    <label for="fullName" class="">
                        Full Name
                    </label>
                    <input type="text" name="fullName" id="fullName" value="{{ Input::old('fullName') }}" placeholder="Full Name" class="form-control">
                    @if ($errors->has('fullName')) <p class="help-block m-b-none">{{ $errors->first('fullName') }}</p> @endif
                </div>
                <input type="hidden" name="jobId" id="jobId" value="{{ $jobPost->autoGeneratedJobId }}" />
                <input type="hidden" name="departmentId" id="departmentId" value="{{ $jobPost->departmentId }}" />
                <div class="form-group <?php  if($errors->has('mobileNumber')){ echo 'has-error'; }?> ">
                    <label for="mobileNumber" class="">
                        Mobile Number
                    </label>
                    <input type="text" name="mobileNumber" id="mobileNumber" value="{{ Input::old('mobileNumber') }}" placeholder="Mobile Number" class="form-control">
                    @if ($errors->has('mobileNumber')) <p class="help-block m-b-none">{{ $errors->first('mobileNumber') }}</p> @endif
                </div>
                <div class="form-group <?php  if($errors->has('picture')){ echo 'has-error'; }?> ">
                    <label for="picture" class="">
                        Picture
                    </label>
                    <input type="file" name="picture" id="picture" value="{{ Input::old('picture') }}" class="form-control">
                    @if ($errors->has('picture')) <p class="help-block m-b-none">{{ $errors->first('picture') }}</p> @endif
                </div>
                <div class="form-group <?php  if($errors->has('cv')){ echo 'has-error'; }?> ">
                    <label for="cv" class="">
                        CV (pdf)
                    </label>
                    <input type="file" name="cv" id="cv" value="{{ Input::old('cv') }}" class="form-control">
                    @if ($errors->has('cv')) <p class="help-block m-b-none">{{ $errors->first('cv') }}</p> @endif
                </div>
            </div>
            <div class="col-lg-6">
               <div class="form-group <?php  if($errors->has('email')){ echo 'has-error'; }?> ">
                   <label for="email" class="">
                       Email
                   </label>
                   <input type="text" name="email" id="email" value="{{ Input::old('email') }}" placeholder="Email" class="form-control">
                   @if ($errors->has('email')) <p class="help-block m-b-none">{{ $errors->first('email') }}</p> @endif
               </div>
                <div class="form-group <?php  if($errors->has('expectedSalary')){ echo 'has-error'; }?> ">
                    <label for="expectedSalary" class="">
                        Expected Salary
                    </label>
                    <input type="text" name="expectedSalary" id="expectedSalary" value="{{ Input::old('expectedSalary') }}" placeholder="Expected Salary" class="form-control">
                    @if ($errors->has('expectedSalary')) <p class="help-block m-b-none">{{ $errors->first('expectedSalary') }}</p> @endif
                </div>
                <div class="form-group <?php  if($errors->has('address')){ echo 'has-error'; }?> ">
                    <label for="address" class="">
                        Address
                    </label>
                    <textarea type="text" name="address" id="address" value="{{ Input::old('address') }}" placeholder="Address" class="form-control"></textarea>
                    @if ($errors->has('address')) <p class="help-block m-b-none">{{ $errors->first('address') }}</p> @endif
                </div>
                <div class="form-group">
                    <label for="" class=""> </label>
                    <button class="btn btn-md btn-success" style="margin-top: 10px;" type="submit">Apply</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection