@extends('layouts.master')
@section('title')
Search Application
@endsection
@section('content')
<div class="content-wrapper">
    <section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="row">
                        <div class="col-lg-2">
                            <h5>Search Application</h5>
                        </div>
                        <div class="col-lg-10">
                            <div class="ibox-tools">
                                <div class="row">
                                    <div class="col-lg-3">
                                        @if (Session::has('message'))
                                          <div class="text-success">{{ Session::get('message') }}</div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    {!! Form::open(array('id'=>'applicationSearchForm', 'class'=>'form', 'role'=>'form')) !!}
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('departmentId')){ echo 'has-error'; }?> ">
                                    <select name="departmentId" id="departmentId" class="form-control">
                                        <option value="">Select a Department</option>
                                        @foreach($departments as $department)
                                            <option value="{{ $department->autoGeneratedDepartmentId }}">{{ $department->departmentName }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            {{--<div class="col-lg-3">--}}
                                {{--<div class="form-group ">--}}
                                    {{--<input type="text" name="jobTitle" id="jobTitle"placeholder="Job Title" class="form-control">--}}
                                {{--</div>--}}
                            {{--</div>--}}
                            {{--<div class="col-lg-2">--}}
                                {{--<div class="form-group ">--}}
                                   {{--<input type="text" name="minExpectedSalary" id="minExpectedSalary" placeholder="Min Expected Salary" class="form-control">--}}
                                {{--</div>--}}
                            {{--</div>--}}
                            {{--<div class="col-lg-2">--}}
                                {{--<div class="form-group">--}}
                                   {{--<input type="text" name="maxExpectedSalary" id="maxExpectedSalary"  placeholder="Max Expected Salary" class="form-control">--}}
                                {{--</div>--}}
                            {{--</div>--}}
                            <div class="col-lg-2">
                                <div class="form-group">
                                   <button type="submit" class="btn btn-sm btn-white">Search</button>
                                </div>
                            </div>
                        </div>
                    {!! Form::close() !!}

                    <script>
                            $("#applicationSearchForm").submit(function(event){
                             // var jobTitle = $('#jobTitle').val();
                              var departmentId = $('#departmentId').val();
                            //  var minExpectedSalary = $('#minExpectedSalary').val();
                             // var maxExpectedSalary = $('#maxExpectedSalary').val();
                              var csrf = "{{ csrf_token() }}";
                              $.post("{{ URL::to('/admin/application/ajax-search-application') }}",
                                          {
                                          //  jobTitle: jobTitle,
                                            departmentId: departmentId,
                                          //  minExpectedSalary: minExpectedSalary,
                                          //  maxExpectedSalary: maxExpectedSalary,
                                            _token: csrf,
                                             headers:{
                                                csrf_token:'<?php echo csrf_token(); ?>'
                                            }
                                          }, function(markup){
                                   $('#showSearchResult').html(markup);
                              });
                                event.preventDefault();
                            });
                    </script>
                    <hr/>
                    <div id="showSearchResult"></div>
                </div>
            </div>
        </div>
        </div>
    </section>
</div>
@endsection