@extends('layouts.frontEndMaster')
@section('sidebar')
<div class="col-lg-3 blog-sidebar">
  <div class="sidebar-module">
    <h4>Departments</h4>
    <ol class="list-unstyled">
    @foreach($departments as $department)
      <li><a href="{{ URL::to('/department/'.$department->autoGeneratedDepartmentId) }}">{{ $department->departmentName }}</a></li>
    @endforeach
    </ol>
  </div>
</div>
@endsection